apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arches.fullname" . }}-env
  labels:
    {{- include "arches.labels" . | nindent 4 }}
data:
  ARCHES_ROOT: "/web_root/arches"
  ARCHES_PROJECT: "{{ .Values.archesProject }}"
  {{- if not (hasKey .Values.env "COMPRESS_ENABLED") }}
  COMPRESS_ENABLED: "True"
  {{- end }}
  {{- if not (hasKey .Values.env "COMPRESS_OFFLINE") }}
  COMPRESS_OFFLINE: "True"
  {{- end }}
  COUCHDB_HOST: {{ printf "%s-couchdb" .Release.Name }}
  COUCHDB_PORT: "5984"
  COUCHDB_USER: admin
  {{- if not (hasKey .Values.env "DJANGO_DEBUG") }}
  DJANGO_DEBUG: "False"
  {{- end }}
  {{- if not (hasKey .Values.env "DJANGO_MODE") }}
  DJANGO_MODE: "PROD"
  {{- end }}
  DJANGO_SETTINGS_MODULE: "{{ .Values.archesProject }}.settings"
  DOMAIN_NAMES: {{ .Values.domainNames }}
  ESHOST: elasticsearch-master
  ESPORT: "9200"
  INSTALL_DEFAULT_CONCEPTS: "False"
  INSTALL_DEFAULT_GRAPHS: "False"
  MOBILE_OAUTH_CLIENT_ID: "{{ default "" .Values.mobileOauthClientId }}"
  STATIC_ROOT: "{{ .Values.staticRoot }}"
  STATIC_URL: "{{ .Values.staticUrl }}"
  PGDBNAME: arches
  PGHOST: {{ printf "%s-postgresql" .Release.Name }}
  PGPORT: "5432"
  PGUSERNAME: postgres
  PYTHONUNBUFFERED: "0"
  TZ: PST
 {{- range $env, $value := .Values.env }}
  {{ $env }}: {{ $value | quote }}
 {{- end }}
