{{- if .Values.tiers.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arches.fullname" . }}-api
  labels:
    tier: api
    {{- include "arches.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: api
      {{- include "arches.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        tier: api
        {{- include "arches.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "arches.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ template "arches.fullname" . }}-env
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['../entrypoint.sh', 'run_api_server']
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
          {{- if or .Values.mappingJsonConfigMap .Values.mappingJson }}
          volumeMounts:
          - name: mapping-file
            mountPath: "/data_root"
            readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if or .Values.mappingJsonConfigMap .Values.mappingJson }}
          - name: WELL_KNOWN_MAPPING_FILE
            value: /data_root/mapping.json
          {{- end }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: {{ default .Values.postgresqlPasswordKey "postgres-password" }}
                name: {{ printf "%s-postgresql" .Release.Name }}
          - name: COUCHDB_PASS
            value: UNSET
            #alueFrom:
            # secretKeyRef:
            #   key: adminPassword
            #   name: {{ printf "%s-couchdb" .Release.Name }}
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                key: celery-broker-url
                name: {{ template "arches.fullname" $ }}
          {{- range $env, $value := .Values.secretEnv }}
          - name: {{ $env }}
            valueFrom:
              secretKeyRef:
                key: {{ $env }}
                name: {{ template "arches.fullname" $ }}-env
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.mappingJsonConfigMap }}
      volumes:
      - name: mapping-file
        configMap:
          name: {{ .Values.mappingJsonConfigMap }}
    {{- else if .Values.mappingJson }}
      volumes:
      - name: mapping-file
        configMap:
          name: {{ template "arches.fullname" $ }}-mapping
    {{- end }}
{{- end }}
