{{- if .Values.ingress.enabled -}}
{{- $fullName := include "arches.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
{{- if semverCompare ">=1.14-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "arches.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  ingressClassName: {{ default .Values.ingress.className "nginx" }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- if semverCompare ">=1.19-0" $kubeVersion }}
          - backend:
              service:
                name: {{ $fullName }}-static
                port:
                  number: {{ $svcPort }}
            path: /static/build/(.*)
            pathType: Prefix
          - backend:
              service:
                name: {{ $fullName }}-static
                port:
                  number: {{ $svcPort }}
            path: /static/?(js/.*)
            pathType: Prefix
          - path: /?(.*)
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            pathType: Prefix
{{- else }}
          - path: /?(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          - backend:
              serviceName: {{ $fullName }}-static
              servicePort: {{ $svcPort }}
            path: /media/?(.*)
{{- end -}}
  {{- end }}
{{- end }}
