apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arches.fullname" . }}-env
  labels:
    {{- include "arches.labels" . | nindent 4 }}
data:
  DJANGO_SECRET_KEY: {{ .Values.djangoSecretKey | b64enc }}
{{- range $env, $value := .Values.secretEnv }}
  {{ $env }}: {{ $value | b64enc }}
{{- end }}
