apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arches.fullname" . }}
  labels:
    {{- include "arches.labels" . | nindent 4 }}
data:
  celery-broker-url: {{ include "arches.rabbitMqUrl" . | b64enc }}
