apiVersion: v2
description: An initial Helm chart for archesproject.org software (unofficial)
name: archesproject
type: application
version: 0.0.3
appVersion: "5.1"
keywords:
  - arches
  - heritage
  - geospatial
  - history
  - conservation
  - django
  - postgis
home: https://www.archesproject.org/
sources:
  - https://github.com/archesproject/arches/
  - https://github.com/flaxandteal/helm-arches/
maintainers:
  - name: Phil Weir
    email: phil.weir@flaxandteal.co.uk
icon: https://www.archesproject.org/wp-content/uploads/2020/02/arches-logo-r-only.svg
engine: gotpl
dependencies:
  - name: elasticsearch
    version: 7.7.0
    repository: https://helm.elastic.co/
  - name: postgresql
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 10.3.2
