apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arches.fullname" . }}-init-db
  labels:
    {{- include "arches.labels" . | nindent 4 }}
data:
  init.sql: |
    {{ template "archesInitUnixSql" . }}
