{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arches.serviceAccountName" . }}
  labels:
{{ include "arches.labels" . | nindent 4 }}
{{- end -}}
