apiVersion: v1
kind: Service
metadata:
  name: {{ include "arches.fullname" . }}
  labels:
    {{- include "arches.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    tier: backend
    {{- include "arches.selectorLabels" . | nindent 4 }}
